version: '3.1'

services:
  auth-drizzle-issue:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - ${PGPORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
